// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace LyraFPSGameplayTags
{
	
	//Input
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	
	//Ability
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ablity_Sprint);
	
	//Cue
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AblityCue_Death_FPS);

	//Status
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprinting);
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_SprintInputHeld);
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_SprintFireBlocked);
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprint_LocalAnim);
	
	//debuff移速
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_MovementDisabled);
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_KnockedDown);
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stunned);
	
	LYRAFPSGAMERUNTIME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerStart_AI);
	
	
	LYRAFPSGAMERUNTIME_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
}
