// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace FPSAnimGameplayTags
{
	
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Jump);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Crouch);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Walk);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Wiggle);
	
	//Offset作用目标
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Target);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Target_Camera);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fragment_Target_ViewModel);
	
	//Event
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JumpStart);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_InAir);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Landed);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_PlayMontage);
	
	//Signal
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Jump);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Land);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_Crouch);
	EASYFPSPROCEDUALANIM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Signal_UnCrouch);
	
	
	
	
	EASYFPSPROCEDUALANIM_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
}